# Generated by Django 4.1.5 on 2023-01-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredit',
            old_name='amout_credit',
            new_name='amount_credit',
        ),
    ]
