# Generated by Django 4.1.5 on 2023-02-01 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0002_rename_amout_credit_usercredit_amount_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
